ajoneedienen/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from web.views import handler404

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("web.urls", namespace="web")),
    path("", include("main.urls", namespace="main")),
    path("accounts/", include("registration.backends.simple.urls")),
    path("sitemap.xml", TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml")),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    *static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

handler404 = handler404

admin.site.site_header = "Ajoneedienen Administration"
admin.site.site_title = "Ajoneedienen Admin Portal"
admin.site.index_title = "Welcome to Ajoneedienen Admin Portal"

main/urls.py
from django.urls import path

from . import views

app_name = "main"

urlpatterns = [
    path("registration/", views.UserRegisterView.as_view(), name="registration_register"),
    path("accounts/register/", views.UserRegisterView.as_view(), name="registration_register"),
    path("accounts/logout/", views.UserLogoutView.as_view(), name="logout"),
    path("home/", views.IndexView.as_view(), name="index"),
    path("dash/admin/", views.AdminIndexView.as_view(), name="admin_index"),
    # profile - restaurant
    path("dash/restaurant/", views.RestaurantIndexView.as_view(), name="restaurant_index"),
    path("blocked/restaurant/", views.RestaurantBlockedView.as_view(), name="restaurant_blocked"),
    path("update/restaurants/", views.AutoRestaurantUpdateView.as_view(), name="auto_restaurant"),
    path("profile/restaurants/", views.RestaurantProfileView.as_view(), name="restaurant_update"),
    # restaurants - crud
    path("restaurants/", views.RestaurantListView.as_view(), name="restaurant_list"),
    path("restaurants/new/", views.RestaurantCreateView.as_view(), name="restaurant_new"),
    path("restaurants/<str:pk>/", views.RestaurantDetailView.as_view(), name="restaurant_detail"),
    path("restaurants/<str:pk>/edit/", views.RestaurantUpdateView.as_view(), name="restaurant_edit"),
    # notifications - crud
    path("notifications/", views.NotificationListView.as_view(), name="notification_list"),
    path("notifications/new/", views.NotificationCreateView.as_view(), name="notification_new"),
    path("notifications/<str:pk>/", views.NotificationDetailView.as_view(), name="notification_detail"),
    path("notifications/<str:pk>/edit/", views.NotificationUpdateView.as_view(), name="notification_edit"),
    path("notifications/<str:pk>/delete/", views.NotificationDeleteView.as_view(), name="notification_delete"),
    # categories - crud
    path("categories/", views.CategoryListView.as_view(), name="category_list"),
    path("categories/new/", views.CategoryCreateView.as_view(), name="category_new"),
    path("categories/<str:pk>/", views.CategoryDetailView.as_view(), name="category_detail"),
    path("categories/<str:pk>/edit/", views.CategoryUpdateView.as_view(), name="category_edit"),
    path("categories/<str:pk>/delete/", views.CategoryDeleteView.as_view(), name="category_delete"),
    # subcategories - crud
    path("subcategories/", views.SubcategoryListView.as_view(), name="subcategory_list"),
    path("subcategories/<str:category_pk>/new/", views.SubcategoryCreateView.as_view(), name="subcategory_new"),
    path("subcategories/<str:pk>/edit/", views.SubcategoryUpdateView.as_view(), name="subcategory_edit"),
    path("subcategories/<str:pk>/delete/", views.SubcategoryDeleteView.as_view(), name="subcategory_delete"),
    # products
    path("products/", views.ProductListView.as_view(), name="product_list"),
    path("products/new/", views.ProductCreateView.as_view(), name="product_new"),
    path("products/<str:pk>/", views.ProductDetailView.as_view(), name="product_detail"),
    path("products/<str:pk>/edit/", views.ProductUpdateView.as_view(), name="product_edit"),
    path("products/<str:pk>/delete/", views.ProductDeleteView.as_view(), name="product_delete"),
    path("cart/<str:pk>/add/", views.AddCartView.as_view(), name="add_to_cart"),
    path("cart/<str:pk>/minus/", views.MinusCartView.as_view(), name="minus_to_cart"),
    path("howitworks/<str:pk>/", views.HowItWorksView.as_view(), name="howitworks"),
    path("option/<str:product_pk>/new/", views.OptionCreateView.as_view(), name="option_new"),
    path("option/<str:pk>/delete/", views.OptionDeleteView.as_view(), name="option_delete"),
    path("option/<str:pk>/edit/", views.OptionUpdateView.as_view(), name="option_edit"),
    # feedback
    path("feedback/", views.FeedbackView.as_view(), name="feedback_list"),
    path("submit_feedback/", views.submit_feedback, name="submit_feedback"),
    path("default_categories/", views.DefaultCategoryListView.as_view(), name="default_category_list"),
    path("default_subcategories/", views.DefaultSubcategoryListView.as_view(), name="default_subcategory_list"),
    path("default_products/", views.DefaultProductListView.as_view(), name="default_product_list"),
    path("mycategory_list/", views.MyCategoryListView.as_view(), name="mycategory_list"),
]

web/urls.py
from django.urls import path

from . import views

app_name = "web"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("catalogue/<str:pk>/", views.RestaurantCatalogueView.as_view(), name="restaurant_catalogue"),
    path("catalogue/<str:pk>/products/", views.RestaurantProductsView.as_view(), name="restaurant_products"),
    path("category/<str:pk>/", views.CategoryView.as_view(), name="category_catalogue"),
    path("checkout/<str:pk>/", views.CheckoutView.as_view(), name="checkout"),
    path("view/catalogue/<str:slug>/", views.RestaurantCatalogueSlugView.as_view(), name="restaurant_slug_catalogue"),
    path("cart_item/plus/", views.CartItemPlusView.as_view(), name="cart_item_plus"),
    path("cart_item/minus/", views.CartItemMinusView.as_view(), name="cart_item_minus"),
]

templates/partials/_footer.html
<footer class="footer">
  <div class="container-fluid d-flex justify-content-between">
    <span class="text-muted d-block text-center text-sm-start d-sm-inline-block">{{footer_text}}</span>
    <span class="float-none float-sm-end mt-1 mt-sm-0 text-end"> {{attribution_text|safe}}</span>
  </div>
</footer>

templates/partials/_navbar.html
{% load static %}
<nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row shadow-sm">
  <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
    <a class="navbar-brand brand-logo" href="{% url 'main:index' %}"><img src="{{logo_url}}" alt="logo" /></a>
    <a class="navbar-brand brand-logo-mini" href="{% url 'main:index' %}"><img
        src="{{favicon_url}}" alt="logo" /></a>
  </div>
  <div class="navbar-menu-wrapper d-flex align-items-stretch">
    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
      <span class="mdi mdi-menu"></span>
    </button>
    
    {% block search %}
    <div class="search-field d-none d-md-block">
      <form class="d-flex align-items-center h-100" action="" method="get">
        <div class="border border-radius input-group">
          <input type="text" class="form-control bg-transparent border-0" placeholder="Search ..." name="q" />
          <button type="submit" class="input-group-prepend bg-transparent">
            <i class="input-group-text border-0 mdi mdi-magnify"></i>
          </button>
        </div>
      </form>
    </div>
    {% endblock %}

    <ul class="navbar-nav navbar-nav-right">

      <li class="nav-item nav-profile dropdown">
        
        <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-bs-toggle="dropdown"
          aria-expanded="false">
          <div class="nav-profile-img">
            <img src="{% static 'main/images/faces/face.jpg' %}" alt="image" />
            <span class="availability-status online"></span>
          </div>
          <div class="nav-profile-text">
            <p class="mb-1 text-black">{{request.user|upper}}</p>
          </div>
        </a>

        <div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
          
          <a class="dropdown-item" href="{% url 'auth_password_change' %}">
            <i class="mdi mdi-cached me-2 text-success"></i>
            Change Password
          </a>
          
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'main:logout' %}">
            <i class="mdi mdi-logout me-2 text-primary"></i> Signout
          </a>
        </div>

      </li>
    </ul>
    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
      data-toggle="offcanvas">
      <span class="mdi mdi-menu"></span>
    </button>
  </div>
</nav>

templates/partials/_sidebar.html
{% load static %}
<nav class="sidebar sidebar-offcanvas" id="sidebar">
  <ul class="nav">
    <li class="nav-item nav-profile">
      <a href="#" class="nav-link">
        <div class="nav-profile-image">
          <img src="{% static 'main/images/faces/face.jpg' %}" alt="profile" />
          <span class="login-status online"></span>
          <!--change to offline or busy as needed-->
        </div>
        <div class="nav-profile-text d-flex flex-column">
          <span class="font-weight-bold mb-2">{{request.user|upper}}</span>
          <span class="text-secondary text-small">{{usertype}}</span>
        </div>
        <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'main:index' %}">
        <span class="menu-title">Dashboard</span>
        <i class="mdi mdi-home menu-icon"></i>
      </a>
    </li>

    {% if request.user.is_superuser %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'main:restaurant_list' %}">
        <span class="menu-title">Restaurants</span>
        <i class="mdi mdi-account menu-icon"></i>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'main:mycategory_list' %}">
        <span class="menu-title">My Categories</span>
        <i class="mdi mdi-layers  menu-icon"></i>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'main:category_list' %}">
        <span class="menu-title">Categories</span>
        <i class="mdi mdi-layers  menu-icon"></i>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'main:subcategory_list' %}">
        <span class="menu-title">Subcategories</span>
        <i class="mdi mdi-layers  menu-icon"></i>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'main:product_list' %}">
        <span class="menu-title">Products</span>
        <i class="mdi mdi-layers  menu-icon"></i>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'main:default_category_list' %}">
        <span class="menu-title">Default Categories</span>
        <i class="mdi mdi-layers  menu-icon"></i>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'main:default_subcategory_list' %}">
        <span class="menu-title">Default Subcategories</span>
        <i class="mdi mdi-layers  menu-icon"></i>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'main:default_product_list' %}">
        <span class="menu-title">Default Products</span>
        <i class="mdi mdi-layers  menu-icon"></i>
      </a>
    </li>

    {% elif request.user.is_staff %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'main:category_list' %}">
        <span class="menu-title">Categories</span>
        <i class="mdi mdi-layers  menu-icon"></i>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'main:subcategory_list' %}">
        <span class="menu-title">Subcategories</span>
        <i class="mdi mdi-layers  menu-icon"></i>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'main:notification_list' %}">
        <span class="menu-title">Notificatons</span>
        <i class="mdi mdi-layers  menu-icon"></i>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'main:feedback_list' %}">
        <span class="menu-title">Feedback</span>
        <i class="mdi mdi-layers  menu-icon"></i>
      </a>
    </li>


    <li class="nav-item">
      <a class="nav-link" href="{% url 'main:restaurant_update' %}">
        <span class="menu-title">Edit Profile</span>
        <i class="mdi mdi-account menu-icon"></i>
      </a>
    </li>

    <li class="nav-item sidebar-actions">
      <span class="nav-link">
        <a href="{% url 'main:product_new' %}" class="btn btn-block btn-lg btn-gradient-primary mt-4">Add Product</a>
      </span>
    </li>
    {% endif %}


  </ul>
</nav>

templates/partials/pagination.html
{% if is_paginated %}
<nav aria-label="Page navigation" class="w-100">
  <ul class="pagination justify-content-center mb-0 flex-wrap w-100">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
    {% if page_obj.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }} <span class="sr-only"></span></span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

templates/partials/suspended.html
<style>
    body {
        height: 100vh;
        margin: 0;
        padding: 50px 0;
        font-family: Arial, sans-serif;
        background-color: #f2f2f2;
    }

    .boxer {
        text-align: center;
        padding: 20px;
        background-color: #fff;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
    }

    h1 {
        margin-top: 0;
        color: #ff0000;
        font-weight: bold;
    }

    p {
        margin-bottom: 20px;
    }

    img {
        max-width: 100%;
        height: auto;
    }
</style>

<div class="container">
    <div class="boxer">
        <img src="https://img.freepik.com/free-vector/tiny-people-standing-near-prohibited-gesture-isolated-flat-illustration_74855-11132.jpg"
            alt="Account Suspended">
        <h1>Account Suspended</h1>
        <p>Your account has been suspended. Please contact customer support for more information.</p>
    </div>
</div>