ajoneedienen/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from web.views import handler404

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("web.urls", namespace="web")),
    path("", include("main.urls", namespace="main")),
    path("accounts/", include("registration.backends.simple.urls")),
    path("sitemap.xml", TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml")),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    *static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

handler404 = handler404

admin.site.site_header = "Ajoneedienen Administration"
admin.site.site_title = "Ajoneedienen Admin Portal"
admin.site.index_title = "Welcome to Ajoneedienen Admin Portal"

main/urls.py
from django.urls import path

from . import views

app_name = "main"

urlpatterns = [
    path("registration/", views.UserRegisterView.as_view(), name="registration_register"),
    path("accounts/register/", views.UserRegisterView.as_view(), name="registration_register"),
    path("accounts/logout/", views.UserLogoutView.as_view(), name="logout"),
    path("home/", views.IndexView.as_view(), name="index"),
    path("dash/admin/", views.AdminIndexView.as_view(), name="admin_index"),
    # profile - restaurant
    path("dash/restaurant/", views.RestaurantIndexView.as_view(), name="restaurant_index"),
    path("blocked/restaurant/", views.RestaurantBlockedView.as_view(), name="restaurant_blocked"),
    path("update/restaurants/", views.AutoRestaurantUpdateView.as_view(), name="auto_restaurant"),
    path("profile/restaurants/", views.RestaurantProfileView.as_view(), name="restaurant_update"),
    # restaurants - crud
    path("restaurants/", views.RestaurantListView.as_view(), name="restaurant_list"),
    path("restaurants/new/", views.RestaurantCreateView.as_view(), name="restaurant_new"),
    path("restaurants/<str:pk>/", views.RestaurantDetailView.as_view(), name="restaurant_detail"),
    path("restaurants/<str:pk>/edit/", views.RestaurantUpdateView.as_view(), name="restaurant_edit"),
    # notifications - crud
    path("notifications/", views.NotificationListView.as_view(), name="notification_list"),
    path("notifications/new/", views.NotificationCreateView.as_view(), name="notification_new"),
    path("notifications/<str:pk>/", views.NotificationDetailView.as_view(), name="notification_detail"),
    path("notifications/<str:pk>/edit/", views.NotificationUpdateView.as_view(), name="notification_edit"),
    path("notifications/<str:pk>/delete/", views.NotificationDeleteView.as_view(), name="notification_delete"),
    # categories - crud
    path("categories/", views.CategoryListView.as_view(), name="category_list"),
    path("categories/new/", views.CategoryCreateView.as_view(), name="category_new"),
    path("categories/<str:pk>/", views.CategoryDetailView.as_view(), name="category_detail"),
    path("categories/<str:pk>/edit/", views.CategoryUpdateView.as_view(), name="category_edit"),
    path("categories/<str:pk>/delete/", views.CategoryDeleteView.as_view(), name="category_delete"),
    # subcategories - crud
    path("subcategories/", views.SubcategoryListView.as_view(), name="subcategory_list"),
    path("subcategories/<str:category_pk>/new/", views.SubcategoryCreateView.as_view(), name="subcategory_new"),
    path("subcategories/<str:pk>/edit/", views.SubcategoryUpdateView.as_view(), name="subcategory_edit"),
    path("subcategories/<str:pk>/delete/", views.SubcategoryDeleteView.as_view(), name="subcategory_delete"),
    # products
    path("products/", views.ProductListView.as_view(), name="product_list"),
    path("products/new/", views.ProductCreateView.as_view(), name="product_new"),
    path("products/<str:pk>/", views.ProductDetailView.as_view(), name="product_detail"),
    path("products/<str:pk>/edit/", views.ProductUpdateView.as_view(), name="product_edit"),
    path("products/<str:pk>/delete/", views.ProductDeleteView.as_view(), name="product_delete"),
    path("cart/<str:pk>/add/", views.AddCartView.as_view(), name="add_to_cart"),
    path("cart/<str:pk>/minus/", views.MinusCartView.as_view(), name="minus_to_cart"),
    path("howitworks/<str:pk>/", views.HowItWorksView.as_view(), name="howitworks"),
    path("option/<str:product_pk>/new/", views.OptionCreateView.as_view(), name="option_new"),
    path("option/<str:pk>/delete/", views.OptionDeleteView.as_view(), name="option_delete"),
    path("option/<str:pk>/edit/", views.OptionUpdateView.as_view(), name="option_edit"),
    # feedback
    path("feedback/", views.FeedbackView.as_view(), name="feedback_list"),
    path("submit_feedback/", views.submit_feedback, name="submit_feedback"),
    path("default_categories/", views.DefaultCategoryListView.as_view(), name="default_category_list"),
    path("default_subcategories/", views.DefaultSubcategoryListView.as_view(), name="default_subcategory_list"),
    path("default_products/", views.DefaultProductListView.as_view(), name="default_product_list"),
    path("mycategory_list/", views.MyCategoryListView.as_view(), name="mycategory_list"),
]

web/urls.py
from django.urls import path

from . import views

app_name = "web"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("catalogue/<str:pk>/", views.RestaurantCatalogueView.as_view(), name="restaurant_catalogue"),
    path("catalogue/<str:pk>/products/", views.RestaurantProductsView.as_view(), name="restaurant_products"),
    path("category/<str:pk>/", views.CategoryView.as_view(), name="category_catalogue"),
    path("checkout/<str:pk>/", views.CheckoutView.as_view(), name="checkout"),
    path("view/catalogue/<str:slug>/", views.RestaurantCatalogueSlugView.as_view(), name="restaurant_slug_catalogue"),
    path("cart_item/plus/", views.CartItemPlusView.as_view(), name="cart_item_plus"),
    path("cart_item/minus/", views.CartItemMinusView.as_view(), name="cart_item_minus"),
]

main/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import View, generic
from django.views.decorators.http import require_POST
from django.views.generic.edit import DeleteView, UpdateView
from registration.views import RegistrationView
from django.http import HttpResponse
from .forms import ProductForm, RestaurantCreateForm, RestaurantEditForm
from .mixins import RestaurantRequiredMixin, SuperuserRequiredMixin
from .models import (
    CartItem,
    Category,
    DefaultCategory,
    DefaultProduct,
    DefaultSubcategory,
    DefualtproductOption,
    Feedback,
    Notification,
    Option,
    Product,
    Restaurant,
    Subcategory,
    VideoPageAd,
)


class UserRegisterView(RegistrationView):
    success_url = reverse_lazy("main:index")

    def register(self, form):
        new_user = User.objects.create_user(
            username=form.cleaned_data["username"],
            password=form.cleaned_data["password1"],
            email=form.cleaned_data["email"],
        )
        new_user.is_staff = True
        new_user.save()

        user = authenticate(
            self.request, username=form.cleaned_data["username"], password=form.cleaned_data["password1"]
        )
        if user is not None:
            login(self.request, user)

        return new_user


class IndexView(LoginRequiredMixin, generic.ListView):
    def get(self, request, *args, **kwargs):
        if request.user.is_superuser:
            return redirect("main:admin_index")
        elif request.user.is_staff:
            return redirect("main:restaurant_index")
        else:
            return redirect("main:shop_index")


class AdminIndexView(LoginRequiredMixin, SuperuserRequiredMixin, generic.ListView):
    context_object_name = "products"
    paginate_by = 50
    template_name = "main/admin_index.html"

    def get_queryset(self):
        return Product.objects.none()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Home"
        context["restaurant_count"] = Restaurant.objects.all().count()
        context["product_count"] = Product.objects.all().count()
        context["category_count"] = Category.objects.all().count()
        context["subcategory_count"] = Subcategory.objects.all().count()
        return context


class RestaurantBlockedView(LoginRequiredMixin, generic.TemplateView):
    template_name = "main/restaurant_blocked.html"


class AutoRestaurantUpdateView(LoginRequiredMixin, generic.FormView):
    model = Restaurant
    template_name = "main/restaurant_update.html"
    success_url = reverse_lazy("main:index")

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_superuser and Restaurant.objects.filter(user=self.request.user).exists():
            return redirect("main:admin_index")
        return super().dispatch(request, *args, **kwargs)

    def get_form(self, form_class=None):
        if Restaurant.objects.filter(user=self.request.user).exists():
            return RestaurantEditForm(
                self.request.POST or None,
                self.request.FILES or None,
                instance=Restaurant.objects.get(user=self.request.user),
            )
        else:
            return RestaurantEditForm(self.request.POST or None, self.request.FILES or None)

    def form_valid(self, form):
        data = form.save()
        data.user = self.request.user
        data.save()
        # Create categories for the restaurant
        # Create categories for the restaurant
        for cat in DefaultCategory.objects.all():
            category_instance = Category.objects.create(
                restaurant=data, name=cat.name, image=cat.image, description=cat.description
            )

            # Create subcategories for each category
            for subcat in DefaultSubcategory.objects.filter(category=cat):
                subcategory_instance = Subcategory.objects.create(
                    category=category_instance, name=subcat.name, description=subcat.description
                )

                # Create products for each subcategory
                for product in DefaultProduct.objects.filter(subcategory=subcat):
                    product_instance = Product.objects.create(
                        subcategory=subcategory_instance,
                        name=product.name,
                        description=product.description,
                        ingredients=product.ingredients,
                        image=product.image,
                        is_popular=product.is_popular,
                        is_vegetarian=product.is_vegetarian,
                        display_foodtype=product.display_foodtype,
                        is_active=product.is_active,
                    )

                    # Create options for each product
                    for option in DefualtproductOption.objects.filter(product=product):
                        Option.objects.create(
                            product=product_instance, section=option.section, name=option.name, price=option.price
                        )

        return super().form_valid(form)

    def form_invalid(self, form):
        print("data is not saved", form.errors)
        return super().form_invalid(form)


class RestaurantProfileView(RestaurantRequiredMixin, generic.FormView):
    model = Restaurant
    template_name = "main/restaurant_profile.html"
    success_url = reverse_lazy("main:index")

    def get_form(self, form_class=None):
        if Restaurant.objects.filter(user=self.request.user).exists():
            return RestaurantEditForm(
                self.request.POST or None,
                self.request.FILES or None,
                instance=Restaurant.objects.get(user=self.request.user),
            )
        else:
            return RestaurantEditForm(self.request.POST or None, self.request.FILES or None)

    def form_valid(self, form):
        data = form.save()
        data.user = self.request.user
        data.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        print("data is not saved", form.errors)
        return super().form_invalid(form)


class RestaurantIndexView(RestaurantRequiredMixin, generic.ListView):
    context_object_name = "products"
    paginate_by = 50
    template_name = "main/restaurant_index.html"

    def get_queryset(self):
        return Product.objects.filter(
            is_active=True, subcategory__category__restaurant=Restaurant.objects.get(user=self.request.user)
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Home"
        restaurant = Restaurant.objects.get(user=self.request.user)
        category_count = Category.objects.filter(restaurant=restaurant).count()
        subcategory_count = Subcategory.objects.filter(category__restaurant=restaurant).count()
        product_count = Product.objects.filter(is_active=True, subcategory__category__restaurant=restaurant).count()
        context["restaurant"] = restaurant
        context["category_count"] = category_count
        context["subcategory_count"] = subcategory_count
        context["product_count"] = product_count
        return context


class RestaurantListView(LoginRequiredMixin, SuperuserRequiredMixin, generic.ListView):
    template_name = "main/restaurant_list.html"
    context_object_name = "restaurants"
    paginate_by = 50

    def get_queryset(self):
        return Restaurant.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Restaurants"
        return context


class RestaurantDetailView(LoginRequiredMixin, SuperuserRequiredMixin, generic.DetailView):
    model = Restaurant
    template_name = "main/restaurant_detail.html"
    context_object_name = "restaurant"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Restaurant"
        return context


class RestaurantUpdateView(LoginRequiredMixin, SuperuserRequiredMixin, UpdateView):
    model = Restaurant
    template_name = "main/restaurant_update.html"
    form_class = RestaurantEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Restaurant"
        return context

    def get_success_url(self):
        return reverse_lazy("main:restaurant_list")


class RestaurantCreateView(LoginRequiredMixin, SuperuserRequiredMixin, generic.CreateView):
    model = Restaurant
    template_name = "main/restaurant_create.html"
    form_class = RestaurantCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Restaurant"
        return context


class CategoryListView(RestaurantRequiredMixin, generic.ListView):
    template_name = "main/category_list.html"
    context_object_name = "categories"
    paginate_by = 100

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Category.objects.all()
        else:
            restaurant = Restaurant.objects.get(user=self.request.user)
            return Category.objects.filter(restaurant=restaurant)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Categories"
        return context


class CategoryDetailView(RestaurantRequiredMixin, generic.DetailView):
    template_name = "main/category_detail.html"
    paginate_by = 50

    def get_queryset(self):

templates/main/category_delete.html
{% extends "base.html" %} {% load static extras crispy_forms_tags i18n %} {% block content %}
<div class="page-header">
    <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white me-2">
            <i class="mdi mdi-home"></i>
        </span>
        Delete Category
    </h3>
    
</div>

<div class="row">
    <div class="col-md-6 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <form method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <div class="buttons mt-5">
              <button type="submit" class="btn btn-gradient-danger">{% trans "Yes, Delete." %}</button>
              <button type="button" onclick="history.back()" class="btn btn-light btn-outline-secondary">{% trans "No, Take me back" %}</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/main/category_detail.html
{% extends "base.html" %} {% load static extras %} {% block content %}
<div class="page-header flex-wrap">
    <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white me-2">
            <i class="mdi mdi-home"></i>
        </span>
        {{object}}
    </h3>
    <nav aria-label="breadcrumb">
        <a href="{% url 'main:subcategory_new' object.pk %}" class="my-1 btn btn-sm btn-primary">New Subcategory</a>
        <a href="{% url 'main:product_new' %}" class="my-1 btn btn-sm btn-primary">New Product</a>
    </nav>

</div>

<div class="row">
    <div class="col-12">

        {% if object.get_subcategories %}
        <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
            <li class="nav-item">
                <button class="nav-link active" id="pills-All-tab" data-bs-toggle="pill" data-bs-target="#pills-All"
                    type="button" role="tab" aria-controls="pills-All" aria-selected="true">All</button>
            </li>
            {% for subcategory in object.get_subcategories %}
            <li class="nav-item">
                <button class="nav-link" id="pills-{{subcategory|slugify}}-tab" data-bs-toggle="pill"
                    data-bs-target="#pills-{{subcategory|slugify}}" type="button" role="tab"
                    aria-controls="pills-{{subcategory|slugify}}" aria-selected="false">
                    {{subcategory}}
                    {% if not subcategory.has_products %}
                    <a href="{{subcategory.get_delete_url}}" class="border-left border-light border-start ms-1 ps-1"><i class="mdi mdi-delete text-danger"></i></a>
                    {% endif %}
                </button>
            </li>
            {% endfor %}
        </ul>

        <div class="tab-content mt-4" id="pills-tabContent">
            
            <div class="tab-pane fade show active" id="pills-All" role="tabpanel" aria-labelledby="pills-All-tab">
                <div class="row">
                    {% for subcategory in object.get_subcategories %}
                    {% for product in subcategory.get_products %}
                    <div class="col-lg-2 col-md-3 col-6 mb-2 px-2">
                        <div class="card">
                            <div class="card-body p-4">
                                <img src="{{product.image.url}}" alt="" class="card-image brdr mx-auto" style="height: 100px;width:100%;object-fit:cover">
                                <h5 class="mb-0 mt-3 fw-bold text-center text-black fz-12">
                                    {{product}}
                                </h5>
                            </div>
                        </div>
                        <div class="card-footer">
                            <div class="button_container text-center">
                                <a href="{{product.get_absolute_url}}" class="btn bg-light btn-sm"><i class="mdi mdi-eye text-primary"></i></a>
                                <a href="{{product.get_edit_url}}" class="btn bg-light btn-sm"><i class="mdi mdi-pencil text-primary"></i></a>
                                <a href="{{product.get_delete_url}}" class="btn bg-light btn-sm"><i class="mdi mdi-delete text-danger"></i></a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    {% endfor %}
                </div>
            </div>

            {% for subcategory in object.get_subcategories %}
            <div class="tab-pane fade" id="pills-{{subcategory|slugify}}" role="tabpanel"
                aria-labelledby="pills-{{subcategory|slugify}}-tab">
                <div class="row">
                    {% for product in subcategory.get_products %}
                    <div class="col-lg-2 col-md-3 col-6 mb-2 px-2">
                        <div class="card">
                            <div class="card-body p-4">
                                <img src="{{product.image.url}}" alt="" class="card-image brdr mx-auto" style="height: 100px;width:100%;object-fit:cover">
                                <h5 class="mb-0 mt-3 fw-bold text-center text-black fz-12">
                                    {{product}}
                                </h5>
                            </div>
                        </div>
                        <div class="card-footer">
                            <div class="button_container text-center">
                                <a href="{{product.get_absolute_url}}" class="btn bg-light btn-sm"><i class="mdi mdi-eye text-primary"></i></a>
                                <a href="{{product.get_edit_url}}" class="btn bg-light btn-sm"><i class="mdi mdi-pencil text-primary"></i></a>
                                <a href="{{product.get_delete_url}}" class="btn bg-light btn-sm"><i class="mdi mdi-delete text-danger"></i></a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}

        </div>
        {% else %}
        <div class="card">
            <div class="card-body">
                <p class="m-0">No Items Exists</p>
            </div>
        </div>
        {% endif %}

        
    </div>

</div>

{% endblock %}

templates/main/category_update.html
{% extends "base.html" %} {% load static extras crispy_forms_tags %} {% block content %}
<div class="page-header">
    <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white me-2">
            <i class="mdi mdi-home"></i>
        </span>
        Edit a Category
    </h3>
    
</div>

<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form|crispy}}
                    <input type="submit" value="Submit" class="btn btn-primary">
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/main/notification_create.html
{% extends "base.html" %} {% load static extras crispy_forms_tags %} {% block content %}
<div class="page-header">
    <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white me-2">
            <i class="mdi mdi-home"></i>
        </span>
        Add a Notification
    </h3>
    
</div>

<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form|crispy}}
                    <input type="submit" value="Submit" class="btn btn-primary">
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/main/option_create.html
{% extends "base.html" %} {% load static extras crispy_forms_tags %} {% block content %}
<div class="page-header">
    <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white me-2">
            <i class="mdi mdi-home"></i>
        </span>
        Add a Option
    </h3>
    
</div>

<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form|crispy}}
                    <input type="submit" value="Submit" class="btn btn-primary">
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/main/option_delete.html
{% extends "base.html" %} {% load static extras crispy_forms_tags i18n %} {% block content %}
<div class="page-header">
    <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white me-2">
            <i class="mdi mdi-home"></i>
        </span>
        Delete Notification
    </h3>
    
</div>

<div class="row">
    <div class="col-md-6 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <form method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <div class="buttons mt-5">
              <button type="submit" class="btn btn-gradient-danger">{% trans "Yes, Delete." %}</button>
              <button type="button" onclick="history.back()" class="btn btn-light btn-outline-secondary">{% trans "No, Take me back" %}</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/main/product_create.html
{% extends "base.html" %} {% load static extras crispy_forms_tags %} {% block content %}
<div class="page-header">
    <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white me-2">
            <i class="mdi mdi-home"></i>
        </span>
        Add a Product
    </h3>
    
</div>

<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form|crispy}}
                    <input type="submit" value="Submit" class="btn btn-primary">
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/main/product_list.html
{% extends "base.html" %} {% load static extras %} {% block content %}
<div class="page-header">
    <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white me-2">
            <i class="mdi mdi-home"></i>
        </span>
        Products
    </h3>
    <nav aria-label="breadcrumb">
        <a href="{% url 'main:product_new' %}" class="btn btn-sm btn-primary">Create New</a>
    </nav>
</div>

<div class="d-flex gap-2 flex-wrap">
    {% for product in products %}
    <div class="" style="width:200px">
        <div class="card">
            <a href="{{product.get_absolute_url}}" class="card-body d-inline-block p-3">
                <img src="{{product.image.url}}" alt="" class="card-image mx-auto" style="height: 80px;">
                <h5 class="mb-0 mt-3 fw-bold text-center text-black fz-12">{{product.name}}</h5>
            </a>
        </div>
        <div class="card-footer">
            <div class="button_container text-center">
                <a href="{{product.get_absolute_url}}" class="btn bg-light btn-sm"><i class="mdi mdi-eye text-info"></i></a>
                <a href="{{product.get_edit_url}}" class="btn bg-light btn-sm"><i class="mdi mdi-pencil text-primary"></i></a>
                <a href="{{product.get_delete_url}}" class="btn bg-light btn-sm"><i class="mdi mdi-delete text-danger"></i></a>
            </div>
        </div>
    </div>

    {% empty %}
    <div class="col-12">
        <div class="card">
            <div class="card-body">                
                <h5 class="m-0">No Products found.</h5>
            </div>
        </div>
    </div>
    {% endfor %}

    {% include "partials/pagination.html" %}
</div>

{% endblock %}

templates/main/restaurant_create.html
{% extends "base.html" %} {% load static extras crispy_forms_tags %} {% block content %}
<div class="page-header">
    <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white me-2">
            <i class="mdi mdi-home"></i>
        </span>
        Add a Restaurant
    </h3>
    
</div>

<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form|crispy}}
                    <input type="submit" value="Submit" class="btn btn-primary">
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/main/restaurant_list.html
{% extends "base.html" %} {% load static extras %} {% block content %}
<div class="page-header">
    <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white me-2">
            <i class="mdi mdi-home"></i>
        </span>
        Restaurants
    </h3>
    <nav aria-label="breadcrumb">
        <a href="{% url 'main:restaurant_new' %}" class="btn btn-sm btn-primary">Create New</a>
    </nav>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                {% if restaurants %}
                <div class="table-responsive">
                    <table class="table table-bordered datatable">

                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>User</th>
                                <th>Phone</th>
                                <th>Address</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        {% for restaurant in restaurants %}
                        <tr>
                            <td>
                                <a href="{{restaurant.get_absolute_url}}">
                                    {% if restaurant.logo %}
                                    <img src="{{restaurant.logo.url}}" alt="logo" class="me-2 shadow-sm" style="max-height: 40px;" />
                                    {% endif %}
                                    {{restaurant.name}}
                                </a>
                            </td>
                            <td>{{restaurant.user}}</td>
                            <td>{{restaurant.phone}}</td>
                            <td>{{restaurant.address}}</td>
                            <td>
                                <a href="{% url 'main:restaurant_edit' restaurant.pk %}"
                                    class="btn btn-sm bg-inverse-primary btn-circle py-1 px-2">
                                    <i class="mdi mdi-pencil"></i>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
                {% else %}
                <p>No restaurants found.</p>
                {% endif %}

                {% include "partials/pagination.html" %}

            </div>
        </div>
    </div>
</div>

{% endblock %}