ajoneedienen/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from web.views import handler404

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("web.urls", namespace="web")),
    path("", include("main.urls", namespace="main")),
    path("accounts/", include("registration.backends.simple.urls")),
    path("sitemap.xml", TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml")),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    *static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

handler404 = handler404

admin.site.site_header = "Ajoneedienen Administration"
admin.site.site_title = "Ajoneedienen Admin Portal"
admin.site.index_title = "Welcome to Ajoneedienen Admin Portal"

main/urls.py
from django.urls import path

from . import views

app_name = "main"

urlpatterns = [
    path("registration/", views.UserRegisterView.as_view(), name="registration_register"),
    path("accounts/register/", views.UserRegisterView.as_view(), name="registration_register"),
    path("accounts/logout/", views.UserLogoutView.as_view(), name="logout"),
    path("home/", views.IndexView.as_view(), name="index"),
    path("dash/admin/", views.AdminIndexView.as_view(), name="admin_index"),
    # profile - restaurant
    path("dash/restaurant/", views.RestaurantIndexView.as_view(), name="restaurant_index"),
    path("blocked/restaurant/", views.RestaurantBlockedView.as_view(), name="restaurant_blocked"),
    path("update/restaurants/", views.AutoRestaurantUpdateView.as_view(), name="auto_restaurant"),
    path("profile/restaurants/", views.RestaurantProfileView.as_view(), name="restaurant_update"),
    # restaurants - crud
    path("restaurants/", views.RestaurantListView.as_view(), name="restaurant_list"),
    path("restaurants/new/", views.RestaurantCreateView.as_view(), name="restaurant_new"),
    path("restaurants/<str:pk>/", views.RestaurantDetailView.as_view(), name="restaurant_detail"),
    path("restaurants/<str:pk>/edit/", views.RestaurantUpdateView.as_view(), name="restaurant_edit"),
    # notifications - crud
    path("notifications/", views.NotificationListView.as_view(), name="notification_list"),
    path("notifications/new/", views.NotificationCreateView.as_view(), name="notification_new"),
    path("notifications/<str:pk>/", views.NotificationDetailView.as_view(), name="notification_detail"),
    path("notifications/<str:pk>/edit/", views.NotificationUpdateView.as_view(), name="notification_edit"),
    path("notifications/<str:pk>/delete/", views.NotificationDeleteView.as_view(), name="notification_delete"),
    # categories - crud
    path("categories/", views.CategoryListView.as_view(), name="category_list"),
    path("categories/new/", views.CategoryCreateView.as_view(), name="category_new"),
    path("categories/<str:pk>/", views.CategoryDetailView.as_view(), name="category_detail"),
    path("categories/<str:pk>/edit/", views.CategoryUpdateView.as_view(), name="category_edit"),
    path("categories/<str:pk>/delete/", views.CategoryDeleteView.as_view(), name="category_delete"),
    # subcategories - crud
    path("subcategories/", views.SubcategoryListView.as_view(), name="subcategory_list"),
    path("subcategories/<str:category_pk>/new/", views.SubcategoryCreateView.as_view(), name="subcategory_new"),
    path("subcategories/<str:pk>/edit/", views.SubcategoryUpdateView.as_view(), name="subcategory_edit"),
    path("subcategories/<str:pk>/delete/", views.SubcategoryDeleteView.as_view(), name="subcategory_delete"),
    # products
    path("products/", views.ProductListView.as_view(), name="product_list"),
    path("products/new/", views.ProductCreateView.as_view(), name="product_new"),
    path("products/<str:pk>/", views.ProductDetailView.as_view(), name="product_detail"),
    path("products/<str:pk>/edit/", views.ProductUpdateView.as_view(), name="product_edit"),
    path("products/<str:pk>/delete/", views.ProductDeleteView.as_view(), name="product_delete"),
    path("cart/<str:pk>/add/", views.AddCartView.as_view(), name="add_to_cart"),
    path("cart/<str:pk>/minus/", views.MinusCartView.as_view(), name="minus_to_cart"),
    path("howitworks/<str:pk>/", views.HowItWorksView.as_view(), name="howitworks"),
    path("option/<str:product_pk>/new/", views.OptionCreateView.as_view(), name="option_new"),
    path("option/<str:pk>/delete/", views.OptionDeleteView.as_view(), name="option_delete"),
    path("option/<str:pk>/edit/", views.OptionUpdateView.as_view(), name="option_edit"),
    # feedback
    path("feedback/", views.FeedbackView.as_view(), name="feedback_list"),
    path("submit_feedback/", views.submit_feedback, name="submit_feedback"),
    path("default_categories/", views.DefaultCategoryListView.as_view(), name="default_category_list"),
    path("default_subcategories/", views.DefaultSubcategoryListView.as_view(), name="default_subcategory_list"),
    path("default_products/", views.DefaultProductListView.as_view(), name="default_product_list"),
    path("mycategory_list/", views.MyCategoryListView.as_view(), name="mycategory_list"),
]

web/urls.py
from django.urls import path

from . import views

app_name = "web"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("catalogue/<str:pk>/", views.RestaurantCatalogueView.as_view(), name="restaurant_catalogue"),
    path("catalogue/<str:pk>/products/", views.RestaurantProductsView.as_view(), name="restaurant_products"),
    path("category/<str:pk>/", views.CategoryView.as_view(), name="category_catalogue"),
    path("checkout/<str:pk>/", views.CheckoutView.as_view(), name="checkout"),
    path("view/catalogue/<str:slug>/", views.RestaurantCatalogueSlugView.as_view(), name="restaurant_slug_catalogue"),
    path("cart_item/plus/", views.CartItemPlusView.as_view(), name="cart_item_plus"),
    path("cart_item/minus/", views.CartItemMinusView.as_view(), name="cart_item_minus"),
]

templates/web/includes/cart.html
{% load tags %}
<div class="osahan-cart-item rounded rounded shadow-sm overflow-hidden bg-white sticky_sidebar mb-3">
    <div class="d-flex border-bottom osahan-cart-item-profile bg-white p-3 justify-content-between">
        <div class="d-flex flex-column">
            <h6 class="mb-1 fw-bold">{{restaurant.name}}</h6>
            <p class="mb-0 small text-muted"><i class="feather-map-pin"></i>{{restaurant.address}}</p>
        </div>
        <button class="btn btn-light toggle ml-auto border-danger" onClick="window.location.reload();"><i class="feather-refresh-cw"></i></button>
    </div>
    {% if cart_items %}
    <div class="bg-white border-bottom py-2">
        {% for cart_item in cart_items %}
        <div class="gold-members d-flex align-items-center justify-content-between px-3 py-2 flex-wrap">
            <div class="d-flex align-items-center mb-2">
                {% if cart_item.product.display_foodtype %}
                {% if cart_item.product.product.is_vegetarian %}
                <div class="fw-bold text-success non_veg">.</div>
                {% else %}
                <div class="fw-bold text-danger non_veg">.</div>
                {% endif %}
                {% endif %}
                <div class="media-body ms-2">
                    <p class="m-0">{{ cart_item.product.product.name }}
                        <span>({{ cart_item.product.name }})</span>
                    </p>
                </div>
            </div>
            <div class="">
                <span class="count-number d-block">
                    <button type="button" class="btn-sm left btn_decrease btn btn-outline-secondary"
                        data-option="{{ cart_item.product.pk }}">
                        <i class="feather-minus"></i>
                    </button>

                    <input class="count-number-input" type="text" readonly
                        value="{% get_qty request.session.session_key cart_item.product restaurant %}">

                    <button type="button" class="btn-sm right btn_increase btn btn-outline-secondary"
                        data-option="{{ cart_item.product.pk }}">
                        <i class="feather-plus"></i>
                    </button>
                </span>
                <p class="text-gray mb-0 float-end ms-2 text-muted small">&#8377;{{ cart_item.total_price }}</p>
            </div>
        </div>
        {% endfor %}

    </div>

    <div class="bg-white p-3">
        <h6 class="fw-bold mb-0">List Total <span class="float-end">&#8377;{{ total_price }}</span></h6>
    </div>

    <div class="p-3">
        <button class="btn btn-success w-100 btn-lg" {% if restaurant.enable_sending == True %} onclick="sendCartToWhatsApp()" {% else %} disabled {% endif %}>Send List <i class="feather-arrow-right"></i></a>
    </div>
    
    
    {% else %}
    <div class="p-3">Your List is Empty</div>
    {% endif %}
</div>

<script>
    function sendCartToWhatsApp() {
        // Get the cart items
        var cartItems = [];
        {% for cart_item in cart_items %}
            cartItems.push("{{ cart_item.product.product.name }} ({{ cart_item.product.name }}) - {{ cart_item.quantity }}");
        {% endfor %}
        
        var restaurant = "{{ restaurant.name }}";

        // Get the current time in AM/PM format
        var currentTime = new Date();
        var hours = currentTime.getHours();
        var minutes = currentTime.getMinutes();
        var ampm = hours >= 12 ? 'PM' : 'AM';
        hours = hours % 12;
        hours = hours ? hours : 12; // Handle midnight (12:00 AM)
        minutes = minutes < 10 ? '0' + minutes : minutes;

        var time = hours + ':' + minutes + ' ' + ampm;

        // Create the message
        var message = restaurant + '\n' + time + "\nMy Menu:\n" + cartItems.join("\n");
    
        // Encode the message for a URL
        var encodedMessage = encodeURIComponent(message);
        var whatsappNumber = "{{ restaurant.phone }}";
        
        // Create the WhatsApp link
        var whatsappLink = "https://api.whatsapp.com/send?phone=" + whatsappNumber + "&text=" + encodedMessage;
    
        // Open WhatsApp in a new tab/window
        window.open(whatsappLink, "_blank");
    }
</script>

templates/web/includes/feedback.html
 <!-- Feedback Modal -->
<div class="modal fade" id="feedbackModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
aria-labelledby="feedbackModalLabel" aria-hidden="true">
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="feedbackModalLabel">Feedback</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <!-- Feedback form -->
            <form id="feedbackForm" method="post" action="{% url 'main:submit_feedback' %}">
                {% csrf_token %}
                
                <input type="hidden" name="restaurant_id" id="restaurant_id" value="{{restaurant.pk}}">
                
                <div class="form-group mb-2">
                    <!-- <label for="reaction">Select Reaction:</label> -->
                    <div class="btn-group" role="group" aria-label="Reaction buttons">
                        <button type="button" data-value="good 😊" class="btn btn-outline-success reaction-btn"
                            onclick="setReaction('good')">😊 Good</button>
                        <button type="button" data-value="satisfied 😐" class="btn btn-outline-warning reaction-btn"
                            onclick="setReaction('satisfied')">😐 Satisfied</button>
                        <button type="button" data-value="bad 😞" class="btn btn-outline-danger reaction-btn"
                            onclick="setReaction('bad')">😞 Bad</button>
                    </div>
                    <input type="hidden" name="reaction" id="reactionInput" value="">
                </div>
                <div class="form-group">
                    
                    <input type="text" name="feedbackName" id="feedbackName" placeholder="name" class="form-control mb-2">
                    <textarea class="form-control" name="feedbackMessage" id="feedbackMessage" rows="4"
                        placeholder="Type your feedback here..."></textarea>
                </div>

                <button type="submit" class="btn btn-primary mt-2">Submit Feedback</button>
            </form>
        </div>
    </div>
</div>
</div> 

templates/web/includes/footer.html
{% load static %}
<footer class="section-footer border-top bg-dark  mt-3 mt-md-5">
    <div class="container top_container">
        <div class="footer-top padding-y py-5">
            <div class="row">
                <aside class="col-md-4 footer-about">
                    <div><img alt="#" src="{% static 'main/images/logo.png' %}" class="logo-footer me-3"></div>
                    <article class="d-flex pb-3">
                        <div>
                            <h6 class="title text-white">About Us</h6>
                            <p class="text-muted">
                                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus quasi velit quae
                                consequatur a aperiam et eaque reprehenderit quo expedita magnam veniam officia dicta
                                cupiditate nihil, ullam pariatur, consectetur consequuntur.
                            </p>
                            <div class="d-flex align-items-center justify-content-start">
                                {% if restaurant.facebook_url %}
                                <a class="sicon me-1" title="Facebook" target="_blank"
                                    href="{{restaurant.facebook_url}}">
                                    <img src="{% static 'web/img/facebook.png' %}"></a>
                                {% endif %}
                                {% if restaurant.instagram_url %}
                                <a class="sicon me-1" title="Instagram" target="_blank"
                                    href="{{restaurant.instagram_url}}">
                                    <img src="{% static 'web/img/instagram.png' %}"></a>
                                {% endif %}
                                {% if restaurant.youtube_url %}
                                <a class="sicon me-1" title="Youtube" target="_blank" href="{{restaurant.youtube_url}}">
                                    <img src="{% static 'web/img/youtube.png' %}"></a>
                                {% endif %}
                                {% if restaurant.twitter_url %}
                                <a class="sicon me-1" title="Twitter" target="_blank" href="{{restaurant.twitter_url}}">
                                    <img src="{% static 'web/img/twitter.png' %}"></a>
                                {% endif %}
                            </div>
                        </div>
                    </article>
                </aside>
                <aside class="col-sm-3 col-md-2 text-white">
                    <h6 class="title">Admin Pages</h6>
                    <ul class="list-unstyled hov_footer">
                        <li> <a href="{% url 'main:restaurant_index' %}" class="text-muted">Dashboard</a>
                        <li> <a href="{% url 'main:restaurant_update' %}" class="text-muted">Update Profile</a>
                        <li> <a href="{% url 'main:category_list' %}" class="text-muted">Categories</a>
                            <li> <a href="{% url 'main:subcategory_list' %}" class="text-muted">Subcategories</a>
                                
                            </ul>
                        </aside>
                        <aside class="col-sm-3 col-md-2 text-white">
                            <h6 class="title">Add New</h6>
                            <ul class="list-unstyled hov_footer">
                        <li> <a href="{% url 'main:category_new' %}" class="text-muted">New Category</a>
                        <li> <a href="{% url 'main:product_list' %}" class="text-muted">Products</a>
                        <li> <a href="{% url 'main:product_new' %}" class="text-muted">New Product</a>
                    </ul>
                </aside>
                <aside class="col-sm-3  col-md-2 text-white">
                    <h6 class="title">For users</h6>
                    <ul class="list-unstyled hov_footer">
                        <li> <a href="{% url 'main:registration_register' %}" class="text-muted"> User register </a></li>
                        <li> <a href="{% url 'auth_login' %}" class="text-muted"> User Login </a></li>
                        <li> <a href="{% url 'auth_logout' %}" class="text-muted"> User Logout </a></li>
                        <li> <a href="{% url 'auth_password_change' %}" class="text-muted">Change Password</a></li>
                    </ul>
                </aside>
                <aside class="col-sm-3  col-md-2 text-white">
                    <h6 class="title">More Pages</h6>
                    <ul class="list-unstyled hov_footer">
                        <li> <a href="#" class="text-muted"> Trending </a></li>
                        <li> <a href="#" class="text-muted"> Most popular </a></li>
                        <li> <a href="#" class="text-muted"> Restaurant Details </a></li>
                        <li> <a href="#" class="text-muted"> Favorites </a></li>
                    </ul>

                </aside>
            </div>

        </div>

    </div>


    <div class="footer-copyright border-top py-3 bg-light">
        <div class="container text-center">
            <p class="mb-0"> © {% now 'Y' %} Ajoneedienen All rights reserved </p>
        </div>
    </div>
</footer>

templates/web/includes/header.html
{% load static %}
<header class="section-header">
    <section class="header-main shadow-sm bg-white">
        <div class="container">
            <div class="row align-items-center py-2">
                <div class="col-4">
                    <a href="{{restaurant.get_web_url}}" class="brand-wrap mb-0">
                        {% if restaurant.logo %}
                        <img class="img-fluid" src="{{restaurant.logo.url}}">
                        {% else %}
                        <img class="img-fluid" src="{% static 'main/images/logo.png' %}">
                        {% endif %}
                    </a>
                </div>
                <div class="col-8">
                    <div class="d-flex align-items-center justify-content-end pe-5">
                        <a href="tel:+91{{restaurant.phone|slugify}}" class="widget-header me-4 text-white btn bg-success">
                            <div class="icon d-flex align-items-center">
                                <i class="feather-phone h6 me-2 mb-0"></i> <span>Call</span>
                            </div>
                        </a>
                        <a href="{% url 'web:checkout' restaurant.pk %}" class="widget-header me-4 text-white btn bg-primary">
                            <div class="icon d-flex align-items-center">
                                <i class="feather-shopping-cart h6 me-2 mb-0"></i> <span>Cart</span>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
</header>

templates/web/includes/header_index.html
{% load static %}
<header class="section-header">
    <section class="header-main shadow-sm bg-white">
        <div class="container">
            <div class="row align-items-center py-2">
                <div class="col-4">
                    <a href="/" class="brand-wrap mb-0">
                        <img class="img-fluid" src="{% static 'main/images/logo.png' %}">
                    </a>
                </div>
                <div class="col-8">
                    <div class="d-flex align-items-center justify-content-end pe-5">
                        <a href="#" class="widget-header me-4 text-dark">
                            <div class="icon d-flex align-items-center">
                                <i class="feather-search h6 me-2 mb-0"></i> <span>Search</span>
                            </div>
                        </a>
                        <a href="{% url 'web:checkout' restaurant.pk %}" class="widget-header me-4 text-white btn bg-primary m-none">
                            <div class="icon d-flex align-items-center">
                                <i class="feather-shopping-cart h6 me-2 mb-0"></i> <span>Cart</span>
                            </div>
                        </a>
                        
                    </div>
                </div>
            </div>
        </div>
    </section>
</header>

templates/web/includes/mobile.html
<div class="osahan-menu-fotter fixed-bottom bg-white px-3 py-2 text-center d-none">
    <div class="row">
        <div class="col">
            <a href="{{restaurant.get_web_url}}" class="text-dark small fw-bold text-decoration-none">
                <p class="h4 m-0"><i class="feather-home text-dark"></i></p>
                Home
            </a>
        </div>
       
        <div class="col bg-white rounded-circle mt-n4 px-3 py-2">
            <div class="bg-danger rounded-circle mt-n0 shadow">
                <a href="{% url 'web:checkout' restaurant.pk %}" class="text-white small fw-bold text-decoration-none">
                    <i class="feather-shopping-cart"></i>
                </a>
            </div>
        </div>
       
        <div class="col">
            <a href="{% url 'main:howitworks' restaurant.pk %}" class="text-dark small fw-bold text-decoration-none">
                <p class="h4 m-0"><i class="feather-play"></i></p>
                How it works
            </a>
        </div>
    </div>
</div>

templates/web/includes/script.html
<script>
    $(document).ready(function () {

        // on .btn_decrease click, decrease quantity by 1 of input sibling, then send ajax request to web:cart_item_plus
        $('.btn_decrease').click(function () {
            var option = $(this).data('option');
            var restaurant_pk = "{{object.restaurant.pk}}";
            var session_key = "{{request.session.session_key}}";
            var input = $(this).siblings('input');
            var qty = parseInt(input.val());
            input.val(qty - 1);
            $.ajax({
                url: "{% url 'web:cart_item_minus' %}",
                data: {
                    'option': option,
                    'restaurant_pk': restaurant_pk,
                    'session_key': session_key,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                dataType: 'json',
                success: function (data) {                   
                    input.val(data.quantity);
                },
                error: function (xhr, status, error) {
                    console.log("AJAX request failed:", status, error);
                }
            }).then(function () {
                console.log("decrease");
                updateCart();
            });
        });

        // on .btn_increase click, increase quantity by 1 of input sibling, then send ajax request to web:cart_item_plus    
        $('.btn_increase').click(function () {
            var option = $(this).data('option');
            var restaurant_pk = "{{object.restaurant.pk}}";
            var session_key = "{{request.session.session_key}}";
            var input = $(this).siblings('input');
            var qty = parseInt(input.val());
            input.val(qty + 1);
            $.ajax({
                url: "{% url 'web:cart_item_plus' %}",
                data: {
                    'option': option,
                    'restaurant_pk': restaurant_pk,
                    'session_key': session_key,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                dataType: 'json',
                success: function (data) {
                    input.val(data.quantity);
                },
                error: function (xhr, status, error) {
                    console.log("AJAX request failed:", status, error);
                }
            }).then(function () {
                console.log("increase");
                updateCart();
            });
        });

        function updateCart() {
            var url = "{% url 'web:checkout_ajax' object.restaurant.pk %}";
            $.ajax({
                url: url,
                dataType: 'html',
                success: function (data) {
                    console.log("got data from " + url);
                    $('#cartMenu').html(data);
                },
                error: function (xhr, status, error) {
                    console.log("AJAX request failed:", status, error);
                }
            });
        }
    });
</script>

templates/web/includes/suspended.html
<style>
    body {
        height: 100vh;
        margin: 0;
        padding: 50px 0;
        font-family: Arial, sans-serif;
        background-color: #f2f2f2;
    }

    .boxer {
        text-align: center;
        padding: 20px;
        background-color: #fff;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
    }

    h1 {
        margin-top: 0;
        color: #ff0000;
        font-weight: bold;
    }

    p {
        margin-bottom: 20px;
    }

    img {
        max-width: 100%;
        height: auto;
    }
</style>

<div class="container">
    <div class="boxer">
        <img src="https://img.freepik.com/free-vector/tiny-people-standing-near-prohibited-gesture-isolated-flat-illustration_74855-11132.jpg" alt="Account Suspended">
        <h1>Account Suspended</h1>
        <p>Your account has been suspended. Please contact customer support for more information.</p>
    </div>
</div>