ajoneedienen/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from web.views import handler404

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("web.urls", namespace="web")),
    path("", include("main.urls", namespace="main")),
    path("accounts/", include("registration.backends.simple.urls")),
    path("sitemap.xml", TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml")),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    *static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

handler404 = handler404

admin.site.site_header = "Ajoneedienen Administration"
admin.site.site_title = "Ajoneedienen Admin Portal"
admin.site.index_title = "Welcome to Ajoneedienen Admin Portal"

main/urls.py
from django.urls import path

from . import views

app_name = "main"

urlpatterns = [
    path("registration/", views.UserRegisterView.as_view(), name="registration_register"),
    path("accounts/register/", views.UserRegisterView.as_view(), name="registration_register"),
    path("accounts/logout/", views.UserLogoutView.as_view(), name="logout"),
    path("home/", views.IndexView.as_view(), name="index"),
    path("dash/admin/", views.AdminIndexView.as_view(), name="admin_index"),
    # profile - restaurant
    path("dash/restaurant/", views.RestaurantIndexView.as_view(), name="restaurant_index"),
    path("blocked/restaurant/", views.RestaurantBlockedView.as_view(), name="restaurant_blocked"),
    path("update/restaurants/", views.AutoRestaurantUpdateView.as_view(), name="auto_restaurant"),
    path("profile/restaurants/", views.RestaurantProfileView.as_view(), name="restaurant_update"),
    # restaurants - crud
    path("restaurants/", views.RestaurantListView.as_view(), name="restaurant_list"),
    path("restaurants/new/", views.RestaurantCreateView.as_view(), name="restaurant_new"),
    path("restaurants/<str:pk>/", views.RestaurantDetailView.as_view(), name="restaurant_detail"),
    path("restaurants/<str:pk>/edit/", views.RestaurantUpdateView.as_view(), name="restaurant_edit"),
    # notifications - crud
    path("notifications/", views.NotificationListView.as_view(), name="notification_list"),
    path("notifications/new/", views.NotificationCreateView.as_view(), name="notification_new"),
    path("notifications/<str:pk>/", views.NotificationDetailView.as_view(), name="notification_detail"),
    path("notifications/<str:pk>/edit/", views.NotificationUpdateView.as_view(), name="notification_edit"),
    path("notifications/<str:pk>/delete/", views.NotificationDeleteView.as_view(), name="notification_delete"),
    # categories - crud
    path("categories/", views.CategoryListView.as_view(), name="category_list"),
    path("categories/new/", views.CategoryCreateView.as_view(), name="category_new"),
    path("categories/<str:pk>/", views.CategoryDetailView.as_view(), name="category_detail"),
    path("categories/<str:pk>/edit/", views.CategoryUpdateView.as_view(), name="category_edit"),
    path("categories/<str:pk>/delete/", views.CategoryDeleteView.as_view(), name="category_delete"),
    # subcategories - crud
    path("subcategories/", views.SubcategoryListView.as_view(), name="subcategory_list"),
    path("subcategories/<str:category_pk>/new/", views.SubcategoryCreateView.as_view(), name="subcategory_new"),
    path("subcategories/<str:pk>/edit/", views.SubcategoryUpdateView.as_view(), name="subcategory_edit"),
    path("subcategories/<str:pk>/delete/", views.SubcategoryDeleteView.as_view(), name="subcategory_delete"),
    # products
    path("products/", views.ProductListView.as_view(), name="product_list"),
    path("products/new/", views.ProductCreateView.as_view(), name="product_new"),
    path("products/<str:pk>/", views.ProductDetailView.as_view(), name="product_detail"),
    path("products/<str:pk>/edit/", views.ProductUpdateView.as_view(), name="product_edit"),
    path("products/<str:pk>/delete/", views.ProductDeleteView.as_view(), name="product_delete"),
    path("cart/<str:pk>/add/", views.AddCartView.as_view(), name="add_to_cart"),
    path("cart/<str:pk>/minus/", views.MinusCartView.as_view(), name="minus_to_cart"),
    path("howitworks/<str:pk>/", views.HowItWorksView.as_view(), name="howitworks"),
    path("option/<str:product_pk>/new/", views.OptionCreateView.as_view(), name="option_new"),
    path("option/<str:pk>/delete/", views.OptionDeleteView.as_view(), name="option_delete"),
    path("option/<str:pk>/edit/", views.OptionUpdateView.as_view(), name="option_edit"),
    # feedback
    path("feedback/", views.FeedbackView.as_view(), name="feedback_list"),
    path("submit_feedback/", views.submit_feedback, name="submit_feedback"),
    path("default_categories/", views.DefaultCategoryListView.as_view(), name="default_category_list"),
    path("default_subcategories/", views.DefaultSubcategoryListView.as_view(), name="default_subcategory_list"),
    path("default_products/", views.DefaultProductListView.as_view(), name="default_product_list"),
    path("mycategory_list/", views.MyCategoryListView.as_view(), name="mycategory_list"),
]

web/urls.py
from django.urls import path

from . import views

app_name = "web"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("catalogue/<str:pk>/", views.RestaurantCatalogueView.as_view(), name="restaurant_catalogue"),
    path("catalogue/<str:pk>/products/", views.RestaurantProductsView.as_view(), name="restaurant_products"),
    path("category/<str:pk>/", views.CategoryView.as_view(), name="category_catalogue"),
    path("checkout/<str:pk>/", views.CheckoutView.as_view(), name="checkout"),
    path("view/catalogue/<str:slug>/", views.RestaurantCatalogueSlugView.as_view(), name="restaurant_slug_catalogue"),
    path("cart_item/plus/", views.CartItemPlusView.as_view(), name="cart_item_plus"),
    path("cart_item/minus/", views.CartItemMinusView.as_view(), name="cart_item_minus"),
]

templates/web/catalogue.html
{% extends 'web/base.html' %}
{% load static %}

{% block header %}
{% include 'web/includes/header.html' %}
{% endblock %}

{% block content %}
<style>
    .float{
        position:fixed;
        width:120px; /* Adjust width as needed */
        height:60px; /* Adjust height as needed */
        bottom:60px;
        right:20px;
        background-color:#dd2e52;
        color:#FFF;
        border-radius:30px; /* Half of the height for circular shape */
        text-align:center;
        line-height: 60px; /* Center the text vertically */
        font-size:18px;
        box-shadow: 2px 2px 3px #999;
        z-index:100;
        text-decoration: none; /* Remove underline */
    }

    .float:hover {
        background-color: #198754; /* Change color on hover */
    }
</style>

{% if restaurant.is_Booknow %}
    {% if restaurant.whatsapp_message %}
        <a href="https://wa.me/{{ restaurant.whatsapp|slugify }}?text={{ restaurant.whatsapp_message }}" class="float" target="_blank">
            Book Now
        </a>
    {% else %}
        <a href="https://wa.me/{{ restaurant.whatsapp|slugify }}?text=Hello%21%20I%20want%20to%20know%20more%20about%20your%20service" class="float" target="_blank">
            Book Now
        </a>
    {% endif %}
{% endif %}
<div class="osahan-home-page">

    <div class="bg-primary p-3 d-none">
        <div class="text-white mb-2">
            <div class="title d-flex justify-content-center">
                <h4 class="fw-bold m-0">{{restaurant}}</h4>
            </div>
        </div>
        <form action="{% url 'web:restaurant_products' restaurant.pk %}" method="get">
            <div class="input-group bg-white rounded shadow-sm mt-0">
                <span class="input-group-text bg-transparent border-0 rounded-0"><i class="feather-search"></i></span>
                <input type="text" class="form-control bg-transparent border-0 rounded-0 px-0 shadow-none" name="q" value="{{request.GET.q|default:''}}"
                    placeholder="Search Services" aria-label="Search ...">
            </div>
        </form>
    </div>

    <div class="container">
        <div class="banner-slider">
            {% for banner in banners %}
            <div class="cat-item px-1 py-3 px-3">
                <a class="d-block text-center shadow-sm" href="javascript:void(0);">
                    <img alt="#" src="{{banner.image.url}}" class="img-fluid rounded">
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

    {% if notifications %}
    <div class="container mt-3 mb-2">
        <div class="row">
            <div class="col-md-8 mt-2">
                <div class="marquee rounded">
                    {% for notification in notifications %}
                        <span class="marquee-text">{{ notification }}</span>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-4 mt-2">
                <form action="{% url 'web:restaurant_products' restaurant.pk %}" method="get">
                    <div class="input-group bg-white rounded shadow-sm mt-0">
                        <span class="input-group-text bg-transparent border-0 rounded-0"><i class="feather-search"></i></span>
                        <input type="text" class="form-control bg-transparent border-0 rounded-0 px-0 shadow-none" name="q" value="{{request.GET.q|default:''}}"
                            placeholder="Search Services" aria-label="Search ...">
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% endif %}


    <div class="container">
        <div class="row px-3">
            {% for category in restaurant.get_categories %}
            <div class="cat-item px-1 py-2 col-xl-2 col-sm-3 col-6">
                <a class="bg-white rounded p-2 text-center shadow-sm p-4 catslider" href="{{category.get_web_url}}">
                    <img alt="" src="{{category.image.url}}" class="img-fluid mb-2 d-block"
                        style="max-height: 80px;margin: 0 auto">
                    <strong class="m-0">{{category.name}}</strong>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>


    <div class="container">
        {% if restaurant.get_populars %}
        <div class="py-3 title d-flex align-items-center">
            <h5 class="m-0">Most popular</h5>
        </div>

        <div class="most_popular mb-3">
            <div class="row">
                {% for product in restaurant.get_populars %}
                {% include 'web/includes/product.html' %}
                {% endfor %}
            </div>
        </div>
        {% endif %}

        <div class="socials text-center my-4">
            <div class="d-flex align-items-center justify-content-center">
                {% if restaurant.phone %}
                <a class="shadow sicon me-1" title="Call" target="_blank" href="tel:{{restaurant.phone|slugify}}">
                    <img src="{% static 'web/img/call.png' %}"></a>
                {% endif %}
                {% if restaurant.whatsapp %}
                <a class="shadow sicon me-1" title="whatsapp" target="_blank" href="https://wa.me/{{restaurant.whatsapp|slugify}}">
                    <img src="{% static 'web/img/whatsapp.png' %}"></a>
                {% endif %}
                {% if restaurant.facebook_url %}
                <a class="shadow sicon me-1" title="Facebook" target="_blank" href="{{restaurant.facebook_url}}">
                    <img src="{% static 'web/img/facebook.png' %}"></a>
                {% endif %}
                {% if restaurant.instagram_url %}
                <a class="shadow sicon me-1" title="Instagram" target="_blank" href="{{restaurant.instagram_url}}">
                    <img src="{% static 'web/img/instagram.png' %}"></a>
                {% endif %}
                {% if restaurant.youtube_url %}
                <a class="shadow sicon me-1" title="Youtube" target="_blank" href="{{restaurant.youtube_url}}">
                    <img src="{% static 'web/img/youtube.png' %}"></a>
                {% endif %}
                {% if restaurant.twitter_url %}
                <a class="shadow sicon me-1" title="Twitter" target="_blank" href="{{restaurant.twitter_url}}">
                    <img src="{% static 'web/img/twitter.png' %}"></a>
                {% endif %}
                <a href="javascript:void(0)" class="shadow sicon me-1" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                    <img src="{% static 'web/img/profile.png' %}"></a>
                </a>

            </div>
        </div>
        {% if restaurant.is_socialmedia %}
         <div class="socials text-center my-4 ">
            <div class="d-grid align-items-center justify-content-end social-media">
                {% if restaurant.location_url %}
                <a class="shadow sicon me-1" title="Location" target="_blank" href="{{restaurant.location_url}}">
                    <img src="{% static 'web/img/location.png' %}"></a>
                {% endif %}
                {% if restaurant.phone %}
                <a class="shadow sicon me-1" title="Call" target="_blank" href=tel:"{{restaurant.phone|slugify}}">
                    <img src="{% static 'web/img/call.png' %}"></a>
                {% endif %}
                {% if restaurant.whatsapp %}
                <a class="shadow sicon me-1" title="whatsapp" target="_blank" href="https://wa.me/{{restaurant.whatsapp|slugify}}">
                    <img src="{% static 'web/img/whatsapp.png' %}"></a>
                {% endif %}
                {% if restaurant.facebook_url %}
                <a class="shadow sicon me-1" title="Facebook" target="_blank" href="{{restaurant.facebook_url}}">
                    <img src="{% static 'web/img/facebook.png' %}"></a>
                {% endif %}
                {% if restaurant.instagram_url %}
                <a class="shadow sicon me-1" title="Instagram" target="_blank" href="{{restaurant.instagram_url}}">
                    <img src="{% static 'web/img/instagram.png' %}"></a>
                {% endif %}
                {% if restaurant.youtube_url %}
                <a class="shadow sicon me-1" title="Youtube" target="_blank" href="{{restaurant.youtube_url}}">
                    <img src="{% static 'web/img/youtube.png' %}"></a>
                {% endif %}
                {% if restaurant.twitter_url %}
                <a class="shadow sicon me-1" title="Twitter" target="_blank" href="{{restaurant.twitter_url}}">
                    <img src="{% static 'web/img/twitter.png' %}"></a>
                {% endif %}
                <a href="javascript:void(0)" class="shadow sicon me-1" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                    <img src="{% static 'web/img/profile.png' %}"></a>
                </a>

            </div>
        </div> 
        {% endif %}
        
    </div>

</div>

{% include 'web/includes/mobile.html' %}


<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">About {{restaurant}}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="d-flex flex-wrap">
                    {% if restaurant.feature_image %}
                    <div class="mb-2">
                        <img alt="" src="{{restaurant.feature_image.url}}" style="width: 100%;overflow: hidden;border-radius: 10px;">
                    </div>
                    {% endif %}
                    <h6>{{restaurant.feature_title|default:""}}</h6>
                    <div class="">
                        <p>
                            {{restaurant.feature_description}}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="text-center">
    <h6>Total Visitors Count : {{restaurant.visitor_count}}</h6>
</div>
<div class="text-center my-4">
    <button id="feedbackButton" type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#feedbackModal">
        Give A Feedback
    </button>
    
</div> 

{% endblock %}

{% block javascript %}
<script>
    $(document).ready(function () {

        // on .btn_decrease click, decrease quantity by 1 of input sibling, then send ajax request to web:cart_item_plus
        $('.btn_decrease').click(function () {
            var option = $(this).data('option');
            var restaurant_pk = "{{restaurant.pk}}";
            var session_key = "{{request.session.session_key}}";
            var input = $(this).siblings('input');
            var qty = parseInt(input.val());
            input.val(qty - 1);
            $.ajax({
                url: "{% url 'web:cart_item_minus' %}",
                data: {
                    'option': option,
                    'restaurant_pk': restaurant_pk,
                    'session_key': session_key,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                dataType: 'json',
                success: function (data) {
                    input.val(data.quantity);
                },
                error: function (xhr, status, error) {
                    console.log("AJAX request failed:", status, error);
                }
            }).then(function () {
                console.log("decrease");
            });
        });

        // on .btn_increase click, increase quantity by 1 of input sibling, then send ajax request to web:cart_item_plus    
        $('.btn_increase').click(function () {
            var option = $(this).data('option');
            var restaurant_pk = "{{restaurant.pk}}";
            var session_key = "{{request.session.session_key}}";
            var input = $(this).siblings('input');
            var qty = parseInt(input.val());
            input.val(qty + 1);
            $.ajax({
                url: "{% url 'web:cart_item_plus' %}",
                data: {
                    'option': option,
                    'restaurant_pk': restaurant_pk,
                    'session_key': session_key,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                dataType: 'json',
                success: function (data) {
                    input.val(data.quantity);
                },
                error: function (xhr, status, error) {
                    console.log("AJAX request failed:", status, error);
                }
            }).then(function () {
                console.log("increase");
            });
        });
    });
</script>



{% endblock javascript %}

templates/web/category.html
{% extends 'web/base.html' %}

{% block header %}
{% include 'web/includes/header.html' %}
{% endblock %}

{% block content %}

<div class="d-none bg-primary p-3">
    <div class="title d-flex justify-content-center mb-2">
        <a class="toggle togglew toggle-2" href="#"><span></span></a>
        <h4 class="fw-bold m-0 text-white">{{object.restaurant}}</h4>
    </div>
    <form action="{% url 'web:restaurant_products' restaurant.pk %}" method="get">
        <div class="input-group bg-white rounded shadow-sm mt-0">
            <span class="input-group-text bg-transparent border-0 rounded-0"><i class="feather-search"></i></span>
            <input type="text" class="form-control bg-transparent border-0 rounded-0 px-0 shadow-none" name="q" value="{{request.GET.q|default:''}}"
                placeholder="Search Services" aria-label="Search ...">
        </div>
    </form>
    
</div>

<div class="offer-section py-4">
    <div class="container position-relative">
        <div class="row">
            <div class="col-md-2">
                <img alt="#" src="{{object.image.url}}" class="restaurant-pic">
            </div>
            <div class="col-md-6 text-white">
                <h2 class="fw-bold">{{object}}</h2>
                <p class="text-white">{{object.description}}</p>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="cat-slider">
        {% for category in object.restaurant.get_categories %}
        <div class="cat-item px-1 py-3">
            <a class="bg-white rounded p-2 text-center shadow-sm catslider" href="{{category.get_web_url}}">
                <img alt="" src="{{category.image.url}}" class="img-fluid mb-2">
                <p class="m-0 small">{{category.name}}</p>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

<div class="container">
    {% if object.get_subcategories %}
    <div class="row">
        <div class="col-12 portfolio-menu mb-0 mt-3">
            <ul class="p-0">
                <li class="btn btn-outline-dark mb-1 active" data-filter="*">All</li>
                {% for subcategory in object.get_subcategories %}
                <li class="btn btn-outline-dark mb-1" data-filter=".{{subcategory.pk}}">{{subcategory}}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% endif %}

    <div class="row">
        <div class="col-md-9 mt-3">
            <div class="row portfolio-item">
                {% for product in object.get_products %}
                {% include 'web/includes/product.html' %}
                {% empty %}
                <p>No Products available</p>
                {% endfor %}
            </div>
        </div>

        <div class="col-md-3 pt-3">
            <div id="cartMenu">
                {% include 'web/includes/cart.html' %}
            </div>
        </div>
    </div>

    <div class="offer-slider">
        {% for banner in catalogue_ads %}
        <div class="cat-item px-1 py-3">
            <a class="d-block text-center shadow-sm" href="javascript:void(0);">
                <img alt="#" src="{{banner.image.url}}" class="img-fluid rounded">
            </a>
        </div>
        {% endfor %}
    </div>


</div>


{% include 'web/includes/mobile.html' %}

{% endblock %}


{% block javascript %}
<script>
    $(document).ready(function () {

        // on .btn_decrease click, decrease quantity by 1 of input sibling, then send ajax request to web:cart_item_plus
        $('.btn_decrease').click(function () {
            var option = $(this).data('option');
            var restaurant_pk = "{{object.restaurant.pk}}";
            var session_key = "{{request.session.session_key}}";
            var input = $(this).siblings('input');
            var qty = parseInt(input.val());
            input.val(qty - 1);
            $.ajax({
                url: "{% url 'web:cart_item_minus' %}",
                data: {
                    'option': option,
                    'restaurant_pk': restaurant_pk,
                    'session_key': session_key,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                dataType: 'json',
                success: function (data) {                   
                    input.val(data.quantity);
                },
                error: function (xhr, status, error) {
                    console.log("AJAX request failed:", status, error);
                }
            }).then(function () {
                console.log("decrease");
            });
        });

        // on .btn_increase click, increase quantity by 1 of input sibling, then send ajax request to web:cart_item_plus    
        $('.btn_increase').click(function () {
            var option = $(this).data('option');
            var restaurant_pk = "{{object.restaurant.pk}}";
            var session_key = "{{request.session.session_key}}";
            var input = $(this).siblings('input');
            var qty = parseInt(input.val());
            input.val(qty + 1);
            $.ajax({
                url: "{% url 'web:cart_item_plus' %}",
                data: {
                    'option': option,
                    'restaurant_pk': restaurant_pk,
                    'session_key': session_key,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                dataType: 'json',
                success: function (data) {
                    input.val(data.quantity);
                },
                error: function (xhr, status, error) {
                    console.log("AJAX request failed:", status, error);
                }
            }).then(function () {
                console.log("increase");
            });
        });
    });
</script>



{% comment %}
<script>
    // Function to encode a string for URL
    function encodeURIString(str) {
        return encodeURIComponent(str);
    }

    // Function to create the WhatsApp message link with item info and total
    function createWhatsAppLink() {
        var phoneNumber = '{{object.restaurant.phone}}';
        var message = 'Hello, I would like to order from ' + encodeURIString('{{ restaurant.name }}') + ' at ' + encodeURIString('{{ restaurant.address }}') + '%0A%0A';
        
        // Initialize the total price
        var totalPrice = 0;
        
        // Loop through cart items and add item details to the message
        {% for cart_item in cart_items %}
            var itemName = encodeURIString('{{ cart_item.product.product.name }}');
            var itemVariant = encodeURIString('{{ cart_item.product.name }}');
            var itemPrice = parseFloat('{{ cart_item.total_price }}');
            
            // Add item price to the total
            totalPrice += itemPrice;
            
            // Append item information to the message
            message += 'Item: ' + itemName + '%0A';
            message += 'Variant: ' + itemVariant + '%0A';
            message += 'Price: ₹' + itemPrice.toFixed(2) + '%0A%0A';
        {% endfor %}
        
        // Add the total price to the message
        message += 'Total Price: ₹' + totalPrice.toFixed(2) + '%0A%0A';
        
        // Construct the WhatsApp message link
        var whatsappLink = 'https://wa.me/' + phoneNumber + '?text=' + message;
        
        return whatsappLink;
    }

    // Get the button element
    var whatsappButton = document.querySelector('.btn-lg');

    // Add a click event listener to the button
    whatsappButton.addEventListener('click', function() {
        // Create the WhatsApp link
        var link = createWhatsAppLink();

        // Open the WhatsApp link in a new tab
        window.open(link);
    });
</script>
{% endcomment %}

{% endblock javascript %}

templates/web/checkout_ajax.html
{% include 'web/includes/cart.html' %}

templates/web/howitworks.html
{% extends 'web/base.html' %}

{% block header %}
{% include 'web/includes/header.html' %}
{% endblock %}

{% block content %}
<div class="osahan-checkout">
    <div class="d-none">
        <div class="bg-primary border-bottom p-3 d-flex align-items-center">
            <a class="toggle togglew toggle-2" href="#"><span></span></a>
            <h4 class="fw-bold m-0 text-white">How It Works</h4>
        </div>
    </div>

    <div class="container position-relative">
        <div class="py-5 row g-4">
            <div class="col-md-8 mx-auto">
                <div class='embed-container'>
                    <iframe src='https://www.youtube.com/embed/3QmEDq0fnWw' frameborder='0'
                        allowfullscreen></iframe>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="banner-slider">
        {% for banner in banners %}
        <div class="cat-item px-1 py-3 px-3">
            <a class="d-block text-center shadow-sm" href="javascript:void(0);">
                <img alt="#" src="{{banner.image.url}}" class="img-fluid rounded">
            </a>
        </div>
        {% endfor %}
    </div>
</div>


{% include 'web/includes/mobile.html' %}


{% endblock %}

templates/web/index.html
{% extends 'web/base.html' %}
{% load static %}
{% block header %}
<header class="section-header d-block">
    <section class="header-main shadow-sm bg-white">
        <div class="container">
            <div class="row align-items-center py-2 justify-content-between">
                <div class="col-4">
                    <a href="/" class="brand-wrap mb-0">
                        <img class="img-fluid" src="{% static 'main/images/logo.png' %}" style="object-fit: contain;">
                    </a>
                </div>
                <div class="col-4">
                    {% if request.user.is_authenticated %}
                    <div class="d-flex align-items-center justify-content-end">
                        <a href="{% url 'main:index' %}" class="widget-header me-2 text-white btn bg-info">
                            <div class="icon d-flex align-items-center">
                                Dashboard</span>
                            </div>
                        </a>
                        <a href="{% url 'auth_logout' %}" class="widget-header me-4 text-white btn bg-primary">
                            <div class="icon d-flex align-items-center">
                                <span>Logout</span>
                            </div>
                        </a>

                    </div>
                    {% else %}
                    <div class="d-flex align-items-center justify-content-end">
                        <a href="{% url 'auth_login' %}" class="widget-header me-2 text-white btn bg-info">
                            <div class="icon d-flex align-items-center">
                                Login</span>
                            </div>
                        </a>
                        <a href="{% url 'main:registration_register' %}"
                            class="widget-header me-4 text-white btn bg-primary">
                            <div class="icon d-flex align-items-center">
                                <span>Register</span>
                            </div>
                        </a>

                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
</header>
{% endblock %}

{% block content %}
<div class="osahan-home-page">

    <div class="bg-primary p-3 d-none">
        <div class="text-white">
            <div class="title d-flex">
                <h4 class="fw-bold m-0">Ajoneedienen</h4>
            </div>
        </div>
    </div>


    <div class="container">

        <div class="offer-slider">
            <div class="cat-item px-1 py-3">
                <a class="d-block text-center shadow-sm" href="javascript:void(0);">
                    <img alt="#" src="/static/web/img/slider.jpg" class="img-fluid rounded">
                </a>
            </div>
        </div>

        {% if badges %}
        <div class="py-3 title d-flex align-items-center">
            <h5 class="m-0">Statistics</h5>
        </div>

        <div class="most_popular mb-5">

            <div class="row">
                {% for badge in badges %}
                <div class="col-md-3 col-md-4 col-6">
                    <div class="card border-danger">
                        <div class="card-body">
                            <h6>{{badge.title}}</h6>
                            <h4 class="text-danger">{{badge.value}}</h4>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
    </div>

</div>
{% endblock %}